SPACESHIP_PROMPT_ORDER=(
  time
  user
  host
  dir
  git
  node
  ruby
  xcode
  swift
  golang
  php
  rust
  docker
  venv
  package
  line_sep
  char
)

## DIR
SPACESHIP_DIR_PREFIX=" "

## GIT
SPACESHIP_GIT_SYMBOL="󰊢 "
SPACESHIP_GIT_PREFIX=" "
SPACESHIP_GIT_STATUS_MODIFIED=" "
SPACESHIP_GIT_STATUS_UNTRACKED=" "
SPACESHIP_GIT_STATUS_STASHED=" "
SPACESHIP_GIT_STATUS_PREFIX=" " 
SPACESHIP_GIT_STATUS_SUFFIX="" 
SPACESHIP_GIT_STATUS_COLOR="yellow"
SPACESHIP_GIT_STATUS_AHEAD="󰁞 "
SPACESHIP_GIT_STATUS_BEHIND="󰁆 "
SPACESHIP_GIT_STATUS_DIVERGED="󰹺 "
SPACESHIP_GIT_STATUS_DELETED=" "

## Package 
SPACESHIP_PACKAGE_SYMBOL=" "
SPACESHIP_PACKAGE_PREFIX=" "
SPACESHIP_PACKAGE_COLOR="grey"

## Node.js 
SPACESHIP_NODE_SYMBOL="󰎙 "
SPACESHIP_NODE_PREFIX=" "

## Docker 
SPACESHIP_DOCKER_SYMBOL=" "
SPACESHIP_DOCKER_PREFIX=" "

## PHP 
SPACESHIP_PHP_SYMBOL=" "
SPACESHIP_PHP_PREFIX=" "

## user
SPACESHIP_USER_SUFFIX="  "

## Execution time
SPACESHIP_EXEC_TIME_PREFIX="  took "

## Hostname
SPACESHIP_HOST_PREFIX="  "
SPACESHIP_HOST_SUFFIX="  "

## Char
SPACESHIP_CHAR_SYMBOL="╰─► "
SPACESHIP_CHAR_SYMBOL_FAILURE="╰─󰞔 "
SPACESHIP_CHAR_SYMBOL_SECONDARY="╰─ "
