require("user.impatient")
require("user.options")
require("user.keymaps")
vim.cmd("runtime ./automappings.vim")
require("user.plugins")
require("user.colorscheme")
require("user.treesitter")
require("user.nvim-tree")
require("user.feline")
require("user.telescope")
require("user.gitsigns")
require("user.comment")
require("user.lsp")
require("user.cmp")
require("user.indentline")
require("user.bufferline")
require("user.autopairs")
