-- vim.cmd([[highlight NormalFloat guibg=NONE]])
-- vim.cmd([[highlight FloatBorder guibg=NONE]])
-- vim.cmd([[highlight Pmenu guibg=NONE]])

require("user.impatient")
require("user.options")
require("user.keymaps")
require("user.autocommands")
require("user.plugins")
require("user.colorscheme")
require("user.treesitter")
require("user.nvim-tree")
require("user.feline")
require("user.telescope")
require("user.gitsigns")
require("user.comment")
require("user.lsp")
require("user.cmp")
require("user.indentline")
require("user.bufferline")
require("user.autopairs")
require("user.todo-comments")
require("user.nvim-notify")
require("user.git-blame")
require("user.vim-visual-multi")
require("user.gitlinker")
require("user.trouble")
